# Generated by Django 3.1 on 2020-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='addToPopular',
            field=models.BooleanField(default=False),
        ),
    ]
