# Generated by Django 3.1 on 2020-09-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_courses_addtopopular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courseDesc',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='courseRating',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='courseTitle',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link5',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link6',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='priceAfterDiscount',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='priceBeforeDiscount',
        ),
    ]
