# Generated by Django 3.1 on 2020-09-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200903_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
