# Generated by Django 3.1 on 2020-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0005_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addToPopular', models.BooleanField(default=False)),
                ('link1', models.CharField(default=0, max_length=250)),
                ('link2', models.CharField(default=0, max_length=250)),
                ('link3', models.CharField(default=0, max_length=250)),
                ('link4', models.CharField(default=0, max_length=250)),
                ('link5', models.CharField(default=0, max_length=250)),
                ('link6', models.CharField(default=0, max_length=250)),
                ('courseTitle', models.CharField(default=0, max_length=250)),
                ('courseDesc', models.CharField(blank=True, max_length=450)),
                ('priceAfterDiscount', models.CharField(default=0, max_length=10)),
                ('courseRating', models.IntegerField(default='0')),
                ('priceBeforeDiscount', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
