# Generated by Django 3.1 on 2020-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificateIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateSerial', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('courseName', models.CharField(max_length=150)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
