# Generated by Django 3.1 on 2020-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_certificateissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateissued',
            name='dateIssued',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
