# Generated by Django 3.1 on 2020-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200909_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='serialNo',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='courses',
            name='testFormUrl',
            field=models.URLField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='certificateissued',
            name='dateIssued',
            field=models.DateTimeField(),
        ),
    ]
