# Generated by Django 3.1 on 2020-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200910_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='successfullPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
