# Generated by Django 3.1 on 2020-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_successfullpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successfullpayments',
            old_name='email',
            new_name='paymentEmail',
        ),
        migrations.RemoveField(
            model_name='successfullpayments',
            name='date',
        ),
        migrations.AddField(
            model_name='successfullpayments',
            name='paymentDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
