# Generated by Django 3.1 on 2020-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200911_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successfullpayments',
            name='paymentDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
