# Generated by Django 3.1 on 2020-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200911_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='beforePaymentCourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=50)),
                ('courseSerial', models.CharField(max_length=50)),
                ('clickDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
